export const actorNames = [
  "Gabriele",
  "Luzziano",
  "Noah Field",
  "Christian",
  "Marcel",
  "Obama",
  "Karina",
  "Alexander",
  "Jan E.",
  "Donald",
  "Deborah",
  "Danu",
  "Aracelli",
  "David",
  "Ariadne",
  "Clementin",
  "Cleopatra",
  "Dionisio",
  "Dorcas",
  "Eleazar",
  "Angelina",
  "Eliezer",
  "Antonella",
  "Devaki",
  "Cloe",
  "Greyson",
  "Clotilde",
  "Ezequiel",
  "Yahaira",
  "Jeremias",
  "Ivy",
  "Jameson",
  "Everett",
  "Bryson",
  "Madeline",
  "Parker",
  "Emmet",
  "Miles",
  "Kassandra",
  "Billy",
  "Lizzie",
  "Austin",
  "Paulette",
  "Cooper",
  "Amanda",
  "Landon",
  "Marina",
  "Sherlock",
  "Vivian",
  "Peyton",
  "Nadine",
  "Angermeier",
  "Carol McP.",
  "Henning",
  "Jesse",
  "Lui P.",
  "Jule",
  "Nahim",
  "Zoe M.",
  "Hans",
  "Evelyn",
  "Jackson",
  "Ella",
  "Carter",
  "Scarlett",
  "Wyatt",
  "Eleanor",
  "Jack",
  "Lillian",
  "Hunter",
  "Christian",
  "Addison",
  "Aubrey",
  "Audrey",
  "Ellie",
  "Julian",
  "Everly",
  "Lincoln",
  "Hazel",
  "Grayson",
  "Lucy",
  "Hudson",
  "Kinsley",
  "Landon",
  "Sheena",
  "Willow",
  "Hellen",
  "Robert",
  "Hailey",
  "Magno",
  "Constanza",
  "Bernhard",
  "Betty",
  "Dalil",
  "Damaris",
  "Eliseo",
  "Eunice",
  "Job",
  "Judit",
  "Leonnel",
];

const hashCode = (s: string) =>
  // eslint-disable-next-line no-bitwise
  s.split("").reduce((a, b) => ((a << 5) - a + b.charCodeAt(0)) | 0, 0);

export const getActors = (
  roles: { role: string; n: string; type: string; services: string[] }[]
) => {
  const actorsWithId = actorNames.map((actor) => ({
    name: actor,
    id: actorNames.indexOf(actor) + 1,
  }));
  return roles.map((role, index) => {
    const shuffled = actorsWithId.sort(
      (a, b) => hashCode(`${a.name}${role.role}`) - hashCode(b.name)
    );
    const selected = shuffled.slice(0, roles.length * 3);
    return {
      role: role.role,
      type: role.type,
      services: role.services,
      actors:
        role.n === "1" || role.type !== "human"
          ? [{ ...selected[index * 3], role: role.role }]
          : [
              { ...selected[index * 3], role: role.role },
              { ...selected[index * 3 + 1], role: role.role },
              { ...selected[index * 3 + 2], role: role.role },
            ],
    };
  });
};
